excluded:
  - "*resource_bundle_accessor*" # SwiftPM Generated
  - ".build/*"

opt_in_rules:
   - missing_docs
   - empty_count
   - empty_string
   - toggle_bool
   - unused_optional_binding
   - valid_ibinspectable
   - modifier_order
   - first_where
   - fatal_error_message
   - force_unwrapping

