# .github/workflows/build-documentation.yml

name: build-documentation

on:
  # Run on push to main branch
  push:
    branches:
      - main

  # Dispatch if triggered using Github (website)
  workflow_dispatch:

jobs:
  Build-documentation:
    runs-on: macos-latest
    steps:
      - name: Build documentation
        uses: 0xWDG/build-documentation@main
